/* Recommended Questions panel */

const { useState: useStateQ } = React;

function QuestionsEmpty() {
  return (
    <div className="q-empty">
      <div className="pulser">
        <IconBrain size={20} />
      </div>
      <div className="msg">Awaiting context</div>
      <div className="sub">
        Suggested clinical follow-ups will appear as evidence accumulates from the conversation.
      </div>
    </div>
  );
}

function LatestQuestion({ q }) {
  return (
    <div className="q-latest">
      <div className="q-latest-eyebrow">
        <span className="dot-pulse"></span>
        Suggested next question
      </div>
      <div className="q-latest-text">{q.hu}</div>
      <div className="q-latest-en">{q.en}</div>
      <div className="q-latest-foot">
        <div className="q-latest-tags">
          {q.tags.map((t) => (
            <span key={t} className="q-hashtag">#{t}</span>
          ))}
        </div>
        <span className="q-priority" data-p={q.p}>
          {q.p === "high" ? "Priority" : q.p === "med" ? "Suggested" : "Optional"}
        </span>
      </div>
    </div>
  );
}

function CollapsedQuestion({ q, idx, expanded, onToggle }) {
  return (
    <div
      className={`q-collapsed ${expanded ? "is-open" : ""}`}
      onClick={onToggle}
      role="button"
      tabIndex={0}
    >
      <div className="q-collapsed-row">
        <span className="q-collapsed-num">{String(idx).padStart(2, "0")}</span>
        <span className="q-collapsed-text">{q.hu}</span>
        <span className="q-collapsed-prio" data-p={q.p}></span>
        <span className="q-collapsed-chev"><IconChevron size={12} /></span>
      </div>
      {expanded && (
        <div className="q-collapsed-detail">
          <div className="q-collapsed-en">{q.en}</div>
          <div className="q-collapsed-tags">
            {q.tags.map((t) => (
              <span key={t} className="q-hashtag">#{t}</span>
            ))}
            <span className="q-priority" data-p={q.p}>
              {q.p === "high" ? "Priority" : q.p === "med" ? "Suggested" : "Optional"}
            </span>
          </div>
        </div>
      )}
    </div>
  );
}

function QuestionsPanel({ questions }) {
  const has = questions.length > 0;
  const [expandedIdx, setExpandedIdx] = useStateQ(null);

  const latest = has ? questions[0] : null;
  const rest = has ? questions.slice(1) : [];

  return (
    <section className="panel" aria-label="Recommended questions">
      <header className="panel-head">
        <div className="panel-title">
          <h2>Recommended questions</h2>
        </div>
        <div className="right-meta">
          <span style={{ fontVariantNumeric: "tabular-nums" }}>{questions.length.toString().padStart(2, "0")} active</span>
        </div>
      </header>
      <div className="panel-body">
        {has ? (
          <div className="q-list-v2">
            <LatestQuestion q={latest} />
            {rest.length > 0 && (
              <>
                <div className="q-list-divider">
                  <span>Earlier suggestions</span>
                </div>
                <div className="q-rest">
                  {rest.map((q, i) => (
                    <CollapsedQuestion
                      key={q.hu}
                      q={q}
                      idx={i + 2}
                      expanded={expandedIdx === i}
                      onToggle={() => setExpandedIdx(expandedIdx === i ? null : i)}
                    />
                  ))}
                </div>
              </>
            )}
          </div>
        ) : (
          <QuestionsEmpty />
        )}
      </div>
      <footer className="panel-foot">
        <IconSpark size={12} />
        <span>Generated by Qwen2.5-Omni-7B · ESC triage protocol</span>
      </footer>
    </section>
  );
}

window.QuestionsPanel = QuestionsPanel;
